### ISSUE TITLE
could not find function "plot_hist"

### ISSUE THREAD

**Issue by orchid00** [tinystats/teacups-giraffes-and-statistics#13]
https://tinystats.github.io/teacups-giraffes-and-statistics/06_standardError.html
Standard Error of the Mean
```

# Set N equal to different sample sizes and test its effect on the sampling distribution
plot_hist(N= )
Error: could not find function "plot_hist"
```

**Comment by dcossyleon** [comment]
Problem seemed to be caused by having `cache = TRUE` in the pre-exercise code chunk. Should be fixed now. Thanks, @orchid00 !
