### ISSUE TITLE
change license to CC BY-NC-SA 4.0?

### ISSUE THREAD

**Issue by davidkane9** [tinystats/teacups-giraffes-and-statistics#17]
Is there a reason you use cc-by-nc-nd instead of a more permissive licence like CC BY-NC-SA 4.0? The reason this matters to me (and others) is that we would like to use your work, but we also want to make some changes. For example, in your material on the normal distribution (which is wonderful), I would like to add some content related to example data that I use in my class. With a permissive license, I can just mix that in. With cc-by-nc-nd, I can't.

**Comment by dcossyleon** [comment]
Thanks, @davidkane9. Per your suggestion, we've gone ahead and changed the license to CC BY-NC-SA 4.0 for all the lesson content. 

We originally used cc-by-nc-nd to keep the art and introductory narrative under something more restrictive, but we've clarified this now in the README.md.

Happy re-mixing --hope your students enjoy it!
